#include<stdio.h>
int main()
{
    int input,a,b,c,d,e,f,g,h,i,j;
        a=12;
        b=7;
        c=3;
        h=0;
        scanf("%d",&input);
        if((input%a==0)||(input%b==0)||(input%c==0))
        {
            if(input%a==0)
            {
                printf("%d*%d=%d\n",a,input/a,input);
            }
            if(input%b==0)
            {
                printf("%d*%d=%d\n",b,input/b,input);
            }
            if(input%c==0)
            {
                printf("%d*%d=%d\n",c,input/c,input);
            }
            printf("YES\n");
            h=1;
        }
        else if(input>a)
        {
            d=input;
            e=input/a;
            for(i=e;i>0;i--)
            {
                d=d-a;
                if((d%b==0)||(d%c==0))
                {
                    if(d%b==0)
                    {
                       printf("%d*%d+%d*%d=%d\n",a,e-i+1,b,d/b,input);
                    }
                    if(d%c==0)
                    {
                       printf("%d*%d+%d*%d=%d\n",a,e-i+1,c,d/c,input);
                    }
                    printf("YES\n");
                    h=1;
                }
                else if(d>b)
                {
                    f=d;
                    g=d/b;
                    for(j=g;j>0;j--)
                    {
                        f=f-b;
                        if(f%c==0)
                        {
                            printf("%d*%d+%d*%d+%d*%d=%d",a,e-i+1,b,g-j+1,c,f/c,input);
                            printf("YES\n");
                            h=1;
                            break;
                        }
                    }
                }
                if(h==1)
                {
                    break;
                }
            }
        }
        else if(input>b)
        {
            d=input;
            e=input/b;
            for(i=e;i>0;i--)
            {
                d=d-b;
                if(d%c==0)
                {
                    printf("%d*%d+%d+%d=%d",b,e-i+1,c,d/c,input);
                    printf("YES\n");
                    break;
                    h==1;
                }
            }
        }
        if(h==0)
        {
            printf("NO\n");
        }
}
